import { NextIntlClientProvider, useMessages } from "next-intl";
import type { Metadata } from "next";
import { Cairo as FontSans } from "next/font/google";
import "../globals.css";

import { cn } from "@/lib/utils";
import { Header } from "@/components/header";
import Footer from "@/components/Footer";
import ModalProvider from "@/provider/ModalProvide";
import { Toaster } from "@/components/ui/toaster";
import useTextDirection from "@/hook/useTextDirection";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{ children: React.ReactNode; params: { locale: string } }>) {
  const direction = useTextDirection(locale);
  const messages = useMessages();

  return (
    <html lang={locale} dir={direction}>
      <body className={cn(fontSans.variable)}>
        <main className="flex h-lvh flex-col bg-background bg-slate-100 font-sans">
          <NextIntlClientProvider messages={messages}>
            <ModalProvider />
            <Header />
            {children}
            <Footer />
            <Toaster />
          </NextIntlClientProvider>
        </main>
      </body>
    </html>
  );
}
